services:
  - type: web
    name: store
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/rails server'
    envVars:
      - key: postgresql://store_db_19wd_user:QqJVWFVjp76bkYqyjVjt77jWcYmj7Ehr@dpg-dajjc4fqj5pc73drt8qg-a/store_db_19wd
        fromDatabase:
          name: store-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: store-db
    plan: free